apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: PostgreSQL-DWH
    type: postgres
    url: postgres-dwh:5432
    database: earthquake
    user: eq_user
    secureJsonData:
      password: eq_password_change_me
    jsonData:
      sslmode: disable
